### ISSUE TITLE
Change default font.

### ISSUE THREAD

**Issue by sgr-ksmt** [krimpedance/KRProgressHUD#1]
KRProgressHUD's default font is `"HiraginoSans-W3, 13.0pt`. But this font is only available **iOS9.0 later**.(Probably, iOS8 earlier versions are use system font, 13.0pt)

I want to change default font-name (and font size) like this:

```swift
public func setDefaultFontName(fontName: String)
public func setDefaultFontSize(size: CGFloat)

// e.g.
KRProgressHUD.setDefaultFontName("HiraKakuProN-W3")
KRProgressHUD.setDefaultFontSize(11.0)

```

Will you please improve??:muscle:

**Comment by krimpedance** [comment]
Sorry, I did’t realize that.

OK. I implement your suggestion.
Please wait a moment :)

**Comment by krimpedance** [comment]
I will close this issue.

I implemented this:

```
public func setDefaultFont(font :UIFont)  // Default font is "HiraginoSans-W3", 13pt
```

I hope this helps you ;)

**Comment by sgr-ksmt** [comment]
@krimpedance 
Thanks for accepting my request!! :smile:
