### ISSUE TITLE
Method to know if progress is actually showing?

### ISSUE THREAD

**Issue by iferrera** [krimpedance/KRProgressHUD#13]
What about adding a method like KRProgressHUD.isVisible to check if it's actually showing or not?

**Comment by krimpedance** [comment]
There isn't the means to check now.
I thought that this check is not important, but what kind of scene do you use it?

**Comment by iferrera** [comment]
I have an APIManager which controls all the requests done. If one fails, I show an alertcontroller to let the user retry or not this request.
Then, I call your progress to show on a UIViewController. What I do, is that if the request fail and the progress was visible, i hide it. Then, if the users wants to retry i'll show it if only if it was visible before. (Not all requests must show the progress)

**Comment by krimpedance** [comment]
In that case, you have only to call `dismiss()`?
`dismiss()` hides progress only when it is displayed.

**Comment by iferrera** [comment]
I think I didn't explain myself, and will be better to show you some code.

`let progressVisible = KRProgressHUD.isVisible()
		if progressVisible {
			**KRProgressHUD.dismiss()**
		}
		let alertController = UIAlertController(title: "AlertRetryRequestTitle".localized(), message: "AlertRetryRequestMessage".localized(), preferredStyle: .Alert)
		alertController.addAction(UIAlertAction(title: "AlertRetryBtnCancel".localized(), style: .Cancel, handler: { (action) in
			if progressVisible {
				**KRProgressHUD.show()**
			}
			retryBlock(retry: false)
		}))
		alertController.addAction(UIAlertAction(title: "AlertRetryBtnRetry".localized(), style: .Default, handler: { (action) in
			if progressVisible {
				**KRProgressHUD.show()**
			}
			retryBlock(retry: true)
		}))
		let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
		appDelegate.window?.rootViewController?.presentViewController(alertController, animated: true, completion: nil)`

**Comment by krimpedance** [comment]
OK. I was able to almost understand it.
I will respond to that right away :)

**Comment by krimpedance** [comment]
I published version 1.5.2 that added parameter.

I'm looking forward to your wonderful application ;)
