### ISSUE TITLE
Change view's center?

### ISSUE THREAD

**Issue by urianawu** [krimpedance/KRProgressHUD#14]
After some digging through your code, I found that you have a sharedView() class func, but somehow i cannot call it by KRProgressHUD.sharedView(). Therefore, I don't see any ways to move the view.

**Comment by krimpedance** [comment]
I don't permit to move progressHUD. Because it isn't necessary to move that in particular. 

hen you'd like to move it at any cost, tell the reason, or please make a custom view using KRActivityIndicator.

**Comment by urianawu** [comment]
hi thanks for immediate response!
i just wanna set the center of HUD to be the center of the whole screen. currently there's a 100 offset that seems arbitrary. I would think that by default, the HUD should be at horizontal and vertical center.

**Comment by krimpedance** [comment]
OK.
I'll add the function to which the center position can be changed.

**Comment by krimpedance** [comment]
I published version 1.6.0 that added `setDefaultCenterPosition(position: CGPoint)`.
And, I changed default center position to device screen's center.

I'm looking forward to your wonderful application ;)
Thanks.
