### ISSUE TITLE
App crash while keyboard is open 

### ISSUE THREAD

**Issue by jayminiphonedev** [krimpedance/KRProgressHUD#16]
Hi,
fist of all thank you very much for KRActivityIndicator.
it's work fine and very nice activity indicator.
but while keyboard is open and show indicator, app is going crash.

Thanks
Jaymin Patel.

**Comment by krimpedance** [comment]
Hi, Patel.
Thank you for your report.

I couldn't reproduce that.
But when HUD was indicated when a keyboard did show, I noticed UIKeyboardDidShowNotification being called infinitely.
I thought the cause was this.

Would you tell me the detailed situation when application crashed?

**Comment by jayminiphonedev** [comment]
Hi
Thanks for response,

In Login form, while enter user name and  passaword and go to login button click  and at that time if keyboard is open and HUD was indicated at that time app id going to crash.

**Comment by krimpedance** [comment]
Absolutely I couldn't reproduce.
Is there other cause?
If it isn't found, try to close a keyboard before indicating HUD.

**Comment by jayminiphonedev** [comment]
i closed keyboard before indicating HUD but still app crash.

**Comment by krimpedance** [comment]
Please show me the code when tapped login button.

**Comment by krimpedance** [comment]
There are no responses.
I close this Issue.
