### ISSUE TITLE
suggest new function

### ISSUE THREAD

**Issue by Mrlovale** [krimpedance/KRProgressHUD#18]
in oc, i use MBProgressHUD for loading. i think a nice text HUD is also needed. so suggest you add a function like showText(text: String)...without any image.

**Comment by krimpedance** [comment]
Thank you for your good suggestion :)
I was convinced that it was necessary.
I'd add it soon.

**Comment by krimpedance** [comment]
I add `showText()` function on 2.1.0 🍺
