### ISSUE TITLE
Progress Hud Add Button 

### ISSUE THREAD

**Issue by ravindrarathore** [krimpedance/KRProgressHUD#20]
Any Custom Method Available for cancel or stop button add in this kr progress hud .
Actual I want add a Button in kr progress hud . 
So If any Solution available then tell Me.
Thanks

**Comment by krimpedance** [comment]
Sorry, there is no intention to which I add a button at present :-<

When you'd like to add it at any cost (and a activity indicator is just used),
I hope that you make custom view using KRActivityIndicatorView (e.g. on xib).

KRActivityIndicatorView is a class included in KRProgressHUD.
How to use: https://github.com/krimpedance/KRActivityIndicator
(The information is old but almost similar.)
