### ISSUE TITLE
The KRProgressHUDMaskType .Clear doesn't seem to work

### ISSUE THREAD

**Issue by schystz** [krimpedance/KRProgressHUD#22]
I want to disable dimming of the background and I figure out I need to set the maskType to `.Clear` to achieve this. But the below code doesn't work:

`KRProgressHUD.showSuccess(message: "Thank you for rating the speaker", maskType: .Clear)`

I still see the same black background while playing around with all mask types (.Black, .White, .Clear). The appetize.io link also displays the same problem - https://appetize.io/app/nw022juw0znkf1n5u6ynga5ntm?device=iphone5s&scale=75&orientation=portrait&osVersion=9.3

**Comment by krimpedance** [comment]
Which version are you using?
The problem is settled already. (ver. 1.4.1)

And, The problem still exists because appetize.io wasn't updated.

**Comment by schystz** [comment]
I was using `1.3.0`. Upgrading to `1.4.1` fixed it! Thanks a lot!!
