### ISSUE TITLE
Only fullscreen?

### ISSUE THREAD

**Issue by andersonlucasg3** [krimpedance/KRProgressHUD#23]
There is only one problem with your library.
What if I just want to lock a specific ViewController with the ProgressHUD?
E.g.: If I have a TabBarController that I can navigate through the tabs.
Currently your library only supports showing in fullscreen mode, locking all the windows bellow it.
Do you think that supporting presentation in a ViewController based root would be a good idea?
If yes, I'm thinking about creating a pull request.
:)

**Comment by krimpedance** [comment]
@andersonlucasg3 
Full screen is the current specification.
But I feel that a case like you should be considered.

I was planning to change code in the near future (After about one week).
Your suggestion would be considered then.

Are you okay with this ??

**Comment by andersonlucasg3** [comment]
Yes, I'm ok with that.
I'll contribute if you're ok.
As soon as I can, I'll make a pull request adding support to ViewController based presentation.
Thanks.

**Comment by krimpedance** [comment]
Hey, @andersonlucasg3 !

KRProgressHUD ver.3.0 is available ;)
`ShowOn(_ viewController:)` method was Implemented.
(https://github.com/krimpedance/KRProgressHUD/blob/master/KRProgressHUD/Classes/KRProgressHUD.swift#L246)

I hope I can be of any help to you :)
Thanks.

**Comment by krimpedance** [comment]
@andersonlucasg3 
This is closed because there is no response.
