### ISSUE TITLE
ShowMessage method text goes out of screen if text is large

### ISSUE THREAD

**Issue by mubashirhussain55** [krimpedance/KRProgressHUD#24]
If I add text in show message method and that text is of more than screen width then it fails to show complete text on the screen.

**Comment by krimpedance** [comment]
@mubashirhussain55 
Which version are you using?
The problem may be settled in ver.3.0.0.

**Comment by krimpedance** [comment]
Please refer :)

Before: ```KRProgressHUD.showText("Message")```

After: ```KRProgressHUD.showMessage("Message line.1 \n Message line.2")```

**Comment by mubashirhussain55** [comment]
Just in case if I want to show text coming as a response to API call and I do not know exactly the string length. In that case, I can not add line breaks manually.

**Comment by krimpedance** [comment]
`label.numberOfLine` is set 0 when call showMessage()
And, hud width  is smaller than a screen width!
So your case is OK.

**Comment by krimpedance** [comment]
@mubashirhussain55 
This is closed because there is no response.
