### ISSUE TITLE
Keyboard is hidden when HUD is shown

### ISSUE THREAD

**Issue by AlexandreMinard** [krimpedance/KRProgressHUD#25]
Hi,

If a keyboard is displayed before showing the HUD, when you show the HUD, the keyboard is hidden (scrolls to bottom of the screen) and when dismissing the HUD, the keyboard comes back from the bottom of the screen.

I didn't find how to avoid this behaviour.
I'd like to have the keyboard permanently displayed under the HUD.
Is that possible?

Regards,
Alexandre

**Comment by krimpedance** [comment]
Hi, @AlexandreMinard .

I think that's impossible.

To indicate keyboard on the HUD may be possible.
(Please try using `KRProgressHUD.showOn(viewController).show()` at ver.3.0.)

Please tell me the situation which indicates a keyboard and HUD together.

**Comment by krimpedance** [comment]
no response.
