### ISSUE TITLE
Spinner stuck if dismissed immediately

### ISSUE THREAD

**Issue by luismachado** [krimpedance/KRProgressHUD#26]
Hello,

Thank you for your work on this pod :)

I'm currently using it to show that the application is calling a REST server so I usually begin() the spinner and when I get the reply from the server I dismiss() it.

However, I have some specific situations where the REST call can be avoided and thus, what I end up doing is begin() the spinner and, a bit down the code, I dismiss it.

What ends up happening is that the spinner goes away but the white box where it spins (and the whole dark layer) don't disappear.

Any idea is this is a bug or if I'm doing something incorrectly.

(ultimately I could devise some logic to stop showing the spinner in the first place but I would like to avoid that, if possible).

Thank you1

**Comment by krimpedance** [comment]
@luismachado 
Thanks for use my pod ;)

Which version are you using?
And, could you show me a related partial code?

**Comment by luismachado** [comment]
@krimpedance 
Hi! I'm using version 3.0.0

Below a simplified snippet of the code:

`fileprivate func fetchAllArticlesAndTags() {
        
        KRProgressHUD.show()
        
        fetchArticlesFor(tabType: tabType, success: { (articles) in
            self.refreshDataSource(articles: articles)
            KRProgressHUD.dismiss()
        }) { (error) in
            KRProgressHUD.dismiss()
        }
    }
    
fileprivate func fetchArticlesFor(tabType: TabType,
                                  success: @escaping ([Article])->(),
                                  failure: @escaping (Error)->()) {
    
    if tabType == .favorites {
        guard let user = User.getCurrentUser() else { success([Article]()); return }

        downloadArticlesByIDs(articleIds: user.favIds, success: { (articles) in // REST API (async call)
            success(articles)
        }, failure: { (error) in
            failure(error)
        })
        
    } else {
        
    }
}`

**Comment by krimpedance** [comment]
@luismachado 

I tried, but it was right movement.
I want you to confirm whether `.dismiss()` is called.

**Comment by krimpedance** [comment]
no response.

**Comment by srinadh-k** [comment]
@luismachado We are also facing same issue. But not sure how often it is occurring.
