### ISSUE TITLE
ActivityIndicator not displaying

### ISSUE THREAD

**Issue by sivishaatrehts** [krimpedance/KRProgressHUD#27]
I use 
`KRProgressHUD.show(withMessage:` `"Loading...")`
 to show a loading indicator, but occasionally the loading indicator (spinner) is not displayed .Ref [image](https://imgur.com/a/B9Mr5).  Reproduced in iOS 10 devices .

**Comment by krimpedance** [comment]
@sivishaatrehts 
Thanks for use my lib.
Please tell me what kind of situation it occurs in.
And if it is possible, please show the code.

**Comment by sivishaatrehts** [comment]
Loading indicator is used when i make a service call and dismiss it when we receive response fro that service call.  As for the code  i use  
`KRProgressHUD.show(withMessage: "Loading...")`       to show the indicator and  `KRProgressHUD.dismiss()` to dismiss the indicator.  I am using the default styles provided and not a customized one.

**Comment by krimpedance** [comment]
Sorry, I can't reproduce that. 😞 
I think it's probably a problem of timing.
I'll test some.
If you found the cause, I want you to report it.

**Comment by krimpedance** [comment]
@sivishaatrehts 
I corrected code a little.
I want you to try test brunch.

```
# Podfile
pod 'KRProgressHUD', :git => 'https://github.com/krimpedance/KRProgressHUD', :branch => 'test'
```

**Comment by sivishaatrehts** [comment]
I tried your new branch, but now nothing happens when i call `KRProgressHUD.show(withMessage: "Loading...")`.

**Comment by krimpedance** [comment]
Before being indicated perfectly, isn't `dismiss` being called ?

You check the order and time the method (`show()` and `dismiss()`) is called and want you to tell me.

**Comment by krimpedance** [comment]
no response.

**Comment by dskibin** [comment]
I have faced that issue. It seems that it's related to z-index of views. KRProgressHUD is showing but not visible -- interface blocked.
