### ISSUE TITLE
Long Message

### ISSUE THREAD

**Issue by haseebjaved1** [krimpedance/KRProgressHUD#29]
showError with Message Cant handle Error Message with long length (like 30+ characters).

**Comment by krimpedance** [comment]
@haseebjaved1 
I think that it is not good to display many sentences in short indication time.
However, I intend to answer a demand to display a long sentence in the near future.

**Comment by krimpedance** [comment]
@haseebjaved1 
Sorry for not responding sooner.
Please use latest version (3.2.0).
