### ISSUE TITLE
".showImage(image, message: msg)" func: image is dim

### ISSUE THREAD

**Issue by Binlogo** [krimpedance/KRProgressHUD#30]
![image](https://user-images.githubusercontent.com/7845507/32775688-c2316ee6-c8f5-11e7-9b3d-46822ddcdb9f.png)
I looked the code, it's set the icon size to 50*50, but if I want to use a custom size, it displays dim.

**Comment by krimpedance** [comment]
@Binlogo 
I released new version (3.1.2).
A custom small picture isn't magnified with this version.

**Comment by Binlogo** [comment]
@krimpedance Thanks a lot.
