### ISSUE TITLE
EXC_BAD_ACCESS on call from a controller inside a UITabBarController's "More" menu item

### ISSUE THREAD

**Issue by gim-** [krimpedance/KRProgressHUD#33]
I have a [UITabBarController](https://developer.apple.com/documentation/uikit/uitabbarcontroller) with more than 5 controllers inside it, which in result puts some of them under the special "More" menu item:
![photo_2018-01-23_10-53-54](https://user-images.githubusercontent.com/1240012/35266388-df87f5ce-002b-11e8-887a-abe76e2ec315.jpg)

And if one of these controllers hidden under "More" calls for example `KRProgressHUD.show(withMessage: "test")` the app will crash with EXC_BAD_ACCESS:
![screen shot 2018-01-23 at 10 36 48](https://user-images.githubusercontent.com/1240012/35266519-3472fe6c-002c-11e8-9a93-f0aab48e0933.png)

While controllers outside of "More" work as expected.

Tested on the iPhone 6 with iOS 11.2.2
KRProgressHUD version: 3.2.0

**Comment by krimpedance** [comment]
@gim- 
I don't know your design in a UITabBarController and how to manage view controllers, so I cannot answer right away.
I will investigate.

Please try this:
`KRProgressHUD.showOn(vc).show(withMessage: "test")`

**Comment by gim-** [comment]
>  `KRProgressHUD.showOn(vc).show(withMessage: "test")`

This works but the position of the progress bar is wrong, it shows up at the top left corner and without dark background. Do I need to set styles and position manually when using `showOn`?

**Comment by gim-** [comment]
A quick update: I just tried to modify the DEMO app but couldn't reproduce this issue there. I'll close it for now and reopen later after I make sure the issue is in the library.

**Comment by gim-** [comment]
@krimpedance Ok, I managed to reproduce it in the DEMO app. This happens when you put navigation controllers inside UITabBarController. You can see it here: https://github.com/gim-/KRProgressHUD/tree/33-reproduce-issue

Launch the DEMO from my `33-reproduce-issue` branch, switch to one of the hidden controllers under "More" and click "Show" button.

**Comment by gim-** [comment]
I don't know if this is the best solution to this problem but this seems to be working in my project:
https://github.com/gim-/KRProgressHUD/commit/eddcce46e8c038ee8e0498c598374b1680ecad49
Are there any possible side effects? If no I can create a PR :)
