### ISSUE TITLE
wanna a smaller HUD 

### ISSUE THREAD

**Issue by Young-Li-90** [krimpedance/KRProgressHUD#35]
a scale property provided to customize the HUD size?

**Comment by krimpedance** [comment]
@GordonLY
Nothing for now.
I will consider :)

**Comment by GorXion** [comment]
@krimpedance 
By the way, can you provide add the custom view?

**Comment by krimpedance** [comment]
@GorXion 
No.
Only icon images can be changed.

**Comment by fzdfy** [comment]
Can you provide an interface to set the gradient of the hudview?
