### ISSUE TITLE
How to disable user interaction with UI while HUD performed?

### ISSUE THREAD

**Issue by NMaks07** [krimpedance/KRProgressHUD#37]
I want to disable user interaction on UI while HUD performs. I have TabBarController, UINavigationControllers. User can interact with them. In some cases in this behavior user can mess UI logic.

**Comment by NMaks07** [comment]
I came up with putting UIApplication.shared.beginIgnoringInteractionEvents() and UIApplication.shared.endIgnoringInteractionEvents() to appropriate completion handlers for show() and dismiss()

**Comment by krimpedance** [comment]
@NMaks07 
Are you using `.showOn(self)` ?
If you use, delete it.
The HUD is indicated with UIWindow, so the user interaction usually becomes invalid.

**Comment by NMaks07** [comment]
thank you ))
