### ISSUE TITLE
not showing properly when using with UITableViewController.

### ISSUE THREAD

**Issue by NMaks07** [krimpedance/KRProgressHUD#38]
it's showing at the upper left corner of UITableViewController.

**Comment by krimpedance** [comment]
@NMaks07 
This is same as #37 .
if you use `showOn(vc)`, HUD is added to vc.view.

**Comment by krimpedance** [comment]
Please replace `KRProgressHUD.showOn(self).show()` to `KRProgressHUD.show()` .

**Comment by NMaks07** [comment]
Ya, it's worked. Thank you good man )).
