### ISSUE TITLE
Compatibility for Swift 4.2 and XCode 10

### ISSUE THREAD

**Issue by SlavcoPetkovski** [krimpedance/KRProgressHUD#42]
Hi.

When can we expect for the library to be compatible for Swift 4.2?
I'm getting errors for kCAMediaTimingFunctionLinear and kCAFillModeForwards, but I don't want to unlock the file.

**Comment by krimpedance** [comment]
@SlavcoPetkovski 
For a short while, please use `dev` branch.
I can update after a little.

**Comment by krimpedance** [comment]
@SlavcoPetkovski 
Please use `3.3.0` :)
