### ISSUE TITLE
KRActivityIndicatorView

### ISSUE THREAD

**Issue by cmhu9985** [krimpedance/KRProgressHUD#43]
Throwing 2 errors after update. 
animation.fillmode = .forwards & animation.timingFunction = CAMediaTimingFunction(name: .linear)

**Comment by krimpedance** [comment]
@cmhu9985 
What is the Swift version?
The latest version of KRProgressHUD (and KRActivityIndicatorView) can only be used in Swift 4.2.

**Comment by krimpedance** [comment]
no response
