### ISSUE TITLE
Not compile with Xcode 10

### ISSUE THREAD

**Issue by clasik** [krimpedance/KRProgressHUD#44]
Not compile with Xcode 10
Swift 4.2
DeplymentTarget iOS 10.0
Cocoapods 1.5.3

Errors:
/Users/.../Pods/KRActivityIndicatorView/KRActivityIndicatorView/Classes/KRActivityIndicatorView.swift:111:62: 'kCAMediaTimingFunctionLinear' has been renamed to 'CAMediaTimingFunctionName.linear'
/QuartzCore.kCAMediaTimingFunctionLinear:3:12: 'kCAMediaTimingFunctionLinear' was obsoleted in Swift 3

/Users/.../Pods/KRActivityIndicatorView/KRActivityIndicatorView/Classes/KRActivityIndicatorView.swift:114:28: 'kCAFillModeForwards' has been renamed to 'CAMediaTimingFillMode.forwards'
/QuartzCore.kCAFillModeForwards:3:12: 'kCAFillModeForwards' was obsoleted in Swift 3

**Comment by krimpedance** [comment]
@clasik 
What version of KRProgressHUD are you using?

**Comment by clasik** [comment]
@krimpedance 
KRActivityIndicatorView (2.1.2)
KRProgressHUD (3.2.2)

Pod file:
```
platform :ios, '10.0'
target 'MYTARGET' do  
    use_frameworks!
    pod 'KRProgressHUD'
end
```

Console log:
```
pod install
Analyzing dependencies
Downloading dependencies
Installing KRActivityIndicatorView (2.1.2)
Installing KRProgressHUD (3.2.2)
```

**Comment by krimpedance** [comment]
@clasik 
ver. 3.2.2 doesn't support Swift 4.2
Please  `pod update`

**Comment by clasik** [comment]
@krimpedance 
All right!! It is Work.
Thanks!
