### ISSUE TITLE
In iOS13 cannot normal show

### ISSUE THREAD

**Issue by zx1262111739** [krimpedance/KRProgressHUD#47]
In iOS13, it only show once and will be impact status bar

**Comment by derekcoder** [comment]
@zx1262111739 I have the same issue. How do you fix it?

**Comment by zx1262111739** [comment]
No fix, myself custom one

**Comment by derekcoder** [comment]
@zx1262111739 Could you please reopen this issue or maybe you can create a new pull request based on your solution?

**Comment by zx1262111739** [comment]
> @zx1262111739 Could you please reopen this issue or maybe you can create a new pull request based on your solution?

I just simple create one can show text widget

**Comment by derekcoder** [comment]
@zx1262111739 thanks.

**Comment by krimpedance** [comment]
@zx1262111739 @derekcoder 
Sorry for my late reply.
Please try `ios-13` branch!

**Comment by derekcoder** [comment]
@krimpedance Got it. Thanks for your reply.

**Comment by ahmedsafadii** [comment]
not working with Xcode 11 GM Seed :( @krimpedance

**Comment by krimpedance** [comment]
@ahmedsafadii 
Sorry, use `3.4.2`.
