### ISSUE TITLE
How to use KRProgressHUD in iMessage App ?

### ISSUE THREAD

**Issue by ib7sandbox** [krimpedance/KRProgressHUD#48]
As iMessage app extension doesn't allow to use "UIApplication.shared.keyWindow" , in this case , how can i use the progresshud in my imessage app ?

**Comment by krimpedance** [comment]
@ib7sandbox 
Please try using `KRProgressHUD.showOn(viewController).show()` .
If it doesn’t work, please use `KRActivityIndicatorView` contains this library. (cf. https://github.com/krimpedance/KRActivityIndicatorView)
