### ISSUE TITLE
Use of undeclared type 'UIWindowScene'

### ISSUE THREAD

**Issue by SohaibSiddique** [krimpedance/KRProgressHUD#49]
Hello,
just updated my pod to 3.4.2 and receiving an error while building "Use of undeclared type 'UIWindowScene'"

here is the code and error image link:

https://imgur.com/upPixUU

**Comment by krimpedance** [comment]
@SohaibSiddique 
Version 3.4.2 can be used on Xcode 11.

**Comment by SohaibSiddique** [comment]
> @SohaibSiddique
> Version 3.4.2 can be used on Xcode 11.

for now, downgrade to 3.4.1 after updating Xcode definitely will update pod to 3.4.2
