### ISSUE TITLE
Progress Hud would not show second time in VC

### ISSUE THREAD

**Issue by SohaibSiddique** [krimpedance/KRProgressHUD#50]
Hello, 
I'm facing an issue with progress hud, it would run second time in any VC and hang the app on a physical device. but seems fine in the simulator.

Simulator: iPhone 7 iOS 13
Device: iPhone 7 iOS 13

**Comment by krimpedance** [comment]
@SohaibSiddique 
Which version are you using? (this lib and xcode)

**Comment by SohaibSiddique** [comment]
pod version: 3.4.2
Xcode 11

**Comment by krimpedance** [comment]
Seems to work fine on my device (iPhone Xs) ...

Could you tell me the detailed situation of the part displaying HUD?

**Comment by WangKunKun** [comment]
I have the same problem

> Seems to work fine on my device (iPhone Xs) ...
> 
> Could you tell me the detailed situation of the part displaying HUD?

I have the same problem··

**Comment by SohaibSiddique** [comment]
now problem resolved for me, 
follow these steps may help you. 

1- Remove app from device and force restart device, 

2- Remove Xcode build device and temporary files from User/Library/Developer

3- Restart your mac and try agin

hope you solve your problem,

**Comment by bhushanbafana** [comment]
getting same issue
Xcode 11
pod version 3.4.2

**Comment by krimpedance** [comment]
@WangKunKun @SohaibSiddique 
Please try `3.4.3` .

**Comment by Sreekanth1995** [comment]
I have the same problem with 3.4.4

**Comment by krimpedance** [comment]
@Sreekanth1995 
Can you show me the smallest project where the problem occurs?

**Comment by Sreekanth1995** [comment]
@krimpedance  I wanted to show Loading indicator while loading web view content.
`import UIKit
import WebKit
import KRProgressHUD

class WebViewController: UIViewController,WKUIDelegate, WKNavigationDelegate {

    var viewModel = WebViewModel()
    var webView: WKWebView!
    override func loadView() {
        super.loadView()
        let webConfiguration = WKWebViewConfiguration()
      //  let frame = CGRect.init(x: 0, y: 64, width: self.view.frame.width, height: self.view.frame.height)
        webView = WKWebView(frame: .zero, configuration: webConfiguration)
        webView.uiDelegate = self
        webView.navigationDelegate = self
        //view.addSubview(webView)
        view = webView
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigationBar()
        self.title = viewModel.getTitle() as String
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        KRProgressHUD.show()
        let url = viewModel.loadURL()
        webView.load(URLRequest(url: url as URL))
        webView.navigationDelegate = self
    }
    func setupNavigationBar() {
        self.navigationController?.navigationBar.setGradientBackground(colors: [UIColor.darkGray, UIColor.darkGray])
        self.navigationItem.setLeftBarButton(backButton, animated: true)
        let titleAttributes = [NSAttributedString.Key.foregroundColor: UIColor.white, NSAttributedString.Key.font: UIFont.normalSizeMediumWeight]
        self.navigationController?.navigationBar.isHidden = false
        self.navigationController?.navigationBar.titleTextAttributes = titleAttributes
    }
    lazy var backButton: UIBarButtonItem = {
        let button = UIBarButtonItem.init(image: #imageLiteral(resourceName: "prevIcon"), style: UIBarButtonItem.Style.plain, target: self, action: #selector(handleBackButtonAction(_:)))
        button.tintColor = UIColor.white
        return button
    }()
    @objc func handleBackButtonAction(_ sender: UIBarButtonItem) {
        if viewModel.isPresent {
            self.dismiss(animated: true, completion: nil)
        } else {
        self.navigationController?.popViewController(animated: true)
        self.navigationController?.navigationBar.setGradientBackground(colors: [UIColor.tvBlue, UIColor.tvGreen])
        }
    }
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        KRProgressHUD.dismiss()
    }
}
`

**Comment by krimpedance** [comment]
@Sreekanth1995 
This works fine for me.
