### ISSUE TITLE
After showing loader other Success or Error view not getting display in Same VC:  Xcode 11

### ISSUE THREAD

**Issue by bhushanbafana** [krimpedance/KRProgressHUD#51]
Hi,
    on api call I'm showing loader and on success I'm showing Success view but its not getting display, I tried too many times.
Xcode version - 11
pod version - 3.4.2

**Comment by krimpedance** [comment]
@bhushanbafana 
Is a demo project same? (under `DEMO/` dir)

Please check with:

```swift
// ViewController.swift:48

        DispatchQueue.main.asyncAfter(deadline: delay) {
            KRProgressHUD.showSuccess(withMessage: "OK")
//            KRProgressHUD.dismiss {
//                print("dismiss() completion handler.")
//            }
        }
```

**Comment by bhushanbafana** [comment]
I have checked in 
viewcontroller.swift: 48
DispatchQueue.main.asyncAfter(deadline: delay) {
            KRProgressHUD.dismiss {
                print("dismiss() completion handler.")
            }
        }

**Comment by krimpedance** [comment]
@bhushanbafana 
Please change to my suggest code and run.

**Comment by bhushanbafana** [comment]
ok

**Comment by bhushanbafana** [comment]
@krimpedance 
its working...thanku

**Comment by krimpedance** [comment]
@bhushanbafana 
Thanks for check.

Please check whether KRProgressHUD files on your project (under `Pods/`) and github files is same.

**Comment by bhushanbafana** [comment]
yes all are same
