### ISSUE TITLE
KRKRProgressHUD.show() not showing ios 13 

### ISSUE THREAD

**Issue by sathamkhussain** [krimpedance/KRProgressHUD#52]
I have updated to the latest, Progress bar not showing in ios 13, iPhone 11 simulator. And also I have selected version swift 5 in the pod.

**Comment by krimpedance** [comment]
@sathamkhussain 
Please run this project.
[Sample.zip](https://github.com/krimpedance/KRProgressHUD/files/3666232/Sample.zip)

**Comment by sathamkhussain** [comment]
@krimpedance the sample one is working fine. What changes do I need to make?

**Comment by krimpedance** [comment]
@sathamkhussain 
First, can you confirm that the files of the pod are the same as your project?
And, I want you to show me the smallest code (or project) that doesn't show HUD.

**Comment by sathamkhussain** [comment]
@krimpedance I have used the below code from your sample.

  func fadeInView(completion: CompletionHandler?) {
        if KRProgressHUD.isVisible {
            hudView.alpha = 0
        } else {
            hudViewController.view.alpha = 0
            if let presentingVC = presentingViewController {
                window.rootViewController = nil
                presentingVC.addChild(hudViewController)
                presentingVC.view.addSubview(hudViewController.view)
                setConstraintsToPresentingVC()
                presentingVC.didMove(toParent: hudViewController)
            } else {
                if #available(iOS 13.0, *) {
                    if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene {
                        window.windowScene = windowScene
                    } else {
                        print("UIWindowScene not found")
                    }
                }
                window.makeKeyAndVisible()
            }
        }

And it's working fine now. You made ios13 check.

**Comment by krimpedance** [comment]
@sathamkhussain 
Thanks for check :)

I've probably made the wrong tag ...
I will create a new tag soon.

**Comment by krimpedance** [comment]
@sathamkhussain 
Please try `3.4.3`

**Comment by sathamkhussain** [comment]
Thanks @krimpedance
