### ISSUE TITLE
In slow internet connection, the loader is not visible.

### ISSUE THREAD

**Issue by hilajqinnovation** [krimpedance/KRProgressHUD#59]
I tried the KTProgressHUD with good internet connection and slow internet connection. And I'm putting the loader before making the API call. And in good internet connection, the loader is showing perfectly. But in low internet connection, the screen gets freezes but loader is not showing. Can you please help me this?

**Comment by krimpedance** [comment]
@hilajqinnovation 
Is it being processed asynchronously?
Please show me an easy code.

**Comment by krimpedance** [comment]
no response

**Comment by hilajqinnovation** [comment]
Sorry for the delay. Yes I'm calling asynchronously.
@IBAction func saveTransaction(_ sender: AnyObject) {
        KRProgressHUD.show()
        self.view.endEditing(true)
        if self.isInternetAvailable {
            //call API
 
        } else {
              //show Warning
        }

}

**Comment by krimpedance** [comment]
@hilajqinnovation 
There seems to be a problem around the API call ...
Can you double check that the API call is not the main thread?

**Comment by hilajqinnovation** [comment]
Ok I will check that. Any way thank you for your reply and sorry for the delay.
