### ISSUE TITLE
Xcode 11.4 Warning "Cannot match several associated values at once..."

### ISSUE THREAD

**Issue by MikeSthlm** [krimpedance/KRProgressHUD#60]
After updating to Xcode 11.4 the following compiler warning appears 3 times

Cannot match several associated values at once, implicitly tupling the associated values and trying to match that instead

in the file KRProgressHUD.swift line 45, 53 and 59

**Comment by SlavcoPetkovski** [comment]
Here is a screenshot. Happens to me also.
![Screen Shot 2020-03-26 at 16 15 31](https://user-images.githubusercontent.com/20534421/77663649-92a36b80-6f7d-11ea-8dbd-4d6e883d728f.png)

**Comment by krimpedance** [comment]
@MikeSthlm @SlavcoPetkovski 
Fix at 3.4.5
