### ISSUE TITLE
showSuccess and callback

### ISSUE THREAD

**Issue by Frozen-Tofu** [krimpedance/KRProgressHUD#64]
It seems that the internal `show` method is not exported, and the exported methods can't meet my need.
In some situation, I'll need to show a HUD to tell like "The order is placed", and then pop to the parent view controller, how can I achieve it?

**Comment by krimpedance** [comment]
Is it a problem to run `popViewController` after `showSuccess` ?

**Comment by Frozen-Tofu** [comment]
No...
